# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='reason_1_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='reason_1_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='service',
            name='reason_2_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='reason_2_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='service',
            name='reason_3_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='reason_3_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='service',
            name='reason_4_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='reason_4_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline',
            field=models.CharField(default='', max_length=400),
        ),
    ]
